### ISSUE TITLE
针对头部左右侧按钮间距问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#100]
你好，能否改造一下头部左右两侧的按钮间距。
如果我头部右侧按钮超过一个的时候，按钮直接的间距太大了。能否可控。
如果不能的话，能否调整一下顶部的原生代码。非常感谢...

**Comment by listenzz** [comment]
你说的是哪个平台呢？

**Comment by lhh-sofy** [comment]
ios跟android都有..

**Comment by listenzz** [comment]
用的是图片还是文字？

**Comment by lhh-sofy** [comment]
用的是图片，文字ios中测试是没有问题的

**Comment by listenzz** [comment]
按钮有个最小宽度限制，宽度不能小于高度，来确保按钮是方的或是胖的，但不能是瘦的，因为这样点击效果不好。

**Comment by listenzz** [comment]
如果觉得间距过大，可以适当调整下图片大小

**Comment by lhh-sofy** [comment]
右侧的三个图片都是48*48的，2倍图。
<img width="457" alt="8967f22a-47eb-4193-8bc9-2c7be3cd0335" src="https://user-images.githubusercontent.com/13582183/51100166-bc0c2780-180f-11e9-9be7-60435014c7f7.png">

**Comment by listenzz** [comment]
嗯，安卓应该没这个问题吧。

**Comment by lhh-sofy** [comment]
安卓也有的，截图如下
![wechatimg110](https://user-images.githubusercontent.com/13582183/51100271-32108e80-1810-11e9-8556-f660a6c1130f.png)
