### ISSUE TITLE
android使用await Navigator.current()时候，会导致闪退

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#101]
你好，使用如下方法时候，android会闪退    
  /**
   * 关闭按钮
   */
  _closePress = () => {
    this.props.navigator.hideModal();
    let that = this;
    async function navigatorModal() {
      const navigator = await Navigator.current();
      that._closePressCallback(navigator);
    }
    // navigatorModal()
  }

**Comment by listenzz** [comment]
Android 堆栈信息？

**Comment by listenzz** [comment]
你在 that._closePressCallback(navigator) 里面做了什么

**Comment by listenzz** [comment]
我这么改了下 playground 里面的 demo，无法重现你说的问题

```
this.props.navigator.hideModal();
async function navigatorModal() {
        const navigator = await Navigator.current();
        navigator.push('Navigation');
}
navigatorModal();
```

**Comment by listenzz** [comment]
这个问题解决没？
