### ISSUE TITLE
showModal无法给里面的组件传参吗

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#102]

**Comment by listenzz** [comment]
可以的呀，通过第三个参数传，但是不能传函数，只能传可序列化为 json 的对象，

```
  showModal(
    moduleName: string,
    requestCode = 0,
    props = {},
    options = {}
  )
```

**Comment by yunuo-tech** [comment]
> 可以的呀，通过第三个参数传，但是不能传函数，只能传可序列化为 json 的对象，
> 
> ```
>   showModal(
>     moduleName: string,
>     requestCode = 0,
>     props = {},
>     options = {}
>   )
> ```

好的，谢谢。 文档里没写，以为不行呢
