### ISSUE TITLE
TabBar 自定义 bug

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#104]
你好，当使用这种方式时候
![tabbar](https://user-images.githubusercontent.com/13582183/51451267-81eed880-1d6f-11e9-980b-0ed2ce48bb13.jpg)。
如果内页中有底部有textinput时候，点击textinput时，会直接替换到到菜单首页..

**Comment by listenzz** [comment]
画个图来演示下？
