### ISSUE TITLE
自定义tabBar的问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#105]
你好 ，当使用自定义tabBar时候，
Navigator.setInterceptor((action, from, to, extras) => {
  console.info(`action:${action} from:${from} to:${to}`);
  // 当返回 true 时，表示你要拦截该操作
  // 譬如用户想要跳到的页面需要登录，你可以在这里验证用户是否已经登录，否则就重定向到登录页面
  return false;
});  这个拦截器没办法拦截 tab 点击事件啦 to没有值   ios测试。安卓未测试

**Comment by listenzz** [comment]
通过代码触发，to 是没有值的，可以利用 extras 里面的 index 来判断要跳到哪个 tab。

**Comment by listenzz** [comment]
计划在后续版本，即使是使用原生 TabBar，即使是手动触发，也不再提供 to 的值。

**Comment by lhh-sofy** [comment]
好的。期待中...
