### ISSUE TITLE
0.11.9 pod是不是忘记打tag了?

### ISSUE THREAD

**Issue by treemore** [listenzz/react-native-navigation-hybrid#107]
你好. 我看你NavigationHybrid.podspec 里面写的是

s.source       = { :git => "https://github.com/listenzz/react-native-navigation-hybrid.git", :tag => "v#{s.version}" }
其中 s.version      = package['version'] 应该等于 package.json里面的版本.
是不是这里忘记提交tag了 ?

**Comment by listenzz** [comment]
这里是没有影响的

**Comment by treemore** [comment]
好像确实没有影响. 
我遇到的问题应该是其他原因造成的.我在观察一下.谢了
