### ISSUE TITLE
能否动态设置tab的图片？

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#11]
有一个需求就是节假日的时候需要替换tab栏的图片，能否提供一个方法修改tab的图片 和选中状态图片

**Comment by listenzz** [comment]
热更新无法解决这个问题吗？

节日图片是通过什么方式下发？

**Comment by VictorYuan666** [comment]
热更新可以但是我想通过接口去获取图片地址

**Comment by listenzz** [comment]
@VictorYuan666 

```
this.props.garden.replaceTabIcon(index, icon, inactiveIcon)
```
提供这样的 api 能满足你的需求吗？

**Comment by VictorYuan666** [comment]
可以的 这个icon可以是require的image也可以是url或是iconfont的name的吧？

**Comment by listenzz** [comment]
和在 tabItem 可配项中的 icon 一样，是一个包含 uri 的对象

**Comment by listenzz** [comment]
已添加  `garden.replaceTabIcon(index, icon, inactiveIcon)`  可以在 Options 这个 tab 的 最后一个条目 *replace tab icon* 体验

```javascript
replaceTabIcon() {
    this.props.garden.replaceTabIcon(
      1,
      { uri: 'blue_solid', scale: PixelRatio.get() }
      // { uri: 'red_ring', scale: PixelRatio.get() }
    );
  }
```
uri 可以是 file:// 这样的格式，指向 icon 的本地缓存

建议先把 icon 缓存到本地，然后再调用此方法
