### ISSUE TITLE
navigationBarColorAndroid 这个值随机生效

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#112]

**Comment by listenzz** [comment]
最好能提供一个 demo

**Comment by NrqhEIcsRi004** [comment]
![2019-01-28 10 11 34](https://user-images.githubusercontent.com/30352961/51845244-c703a380-2349-11e9-9d6d-3c5f768bd6e6.png)

**Comment by NrqhEIcsRi004** [comment]
我这边好像是这样写导致的，setStyle好像不能放在函数里面

**Comment by NrqhEIcsRi004** [comment]
https://github.com/NrqhEIcsRi004/react-native-navigation-hybrid/commit/5f03af41d2535fa7eac68469dc678618e91762f5

**Comment by NrqhEIcsRi004** [comment]
似乎是顺序问题

**Comment by listenzz** [comment]
是的，有顺序限制，在 Android，setStyle 只会在第一次调用时生效。

**Comment by NrqhEIcsRi004** [comment]
好像在Android上setStyle必须要放在startRegisterComponent之前
