### ISSUE TITLE
自带的闪屏第一次好像没有显示

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#115]
使用npm run run:android 后没有显示闪屏，但是后面进入都会显示

**Comment by NrqhEIcsRi004** [comment]
还有请问一下自带闪屏关闭时机是什么时候？

**Comment by NrqhEIcsRi004** [comment]
闪屏与显示之间会白一下，是不是内容太多？

**Comment by treemore** [comment]
onReactModuleRegisterCompleted 例子里面这个回调适合没走.  而且就是 SplashActivity 的finish 不调用闪屏也会自动消失
