### ISSUE TITLE
navigator.isStackRoot is undefined

### ISSUE THREAD

**Issue by treemore** [listenzz/react-native-navigation-hybrid#118]
└── react-native-navigation-hybrid@0.12.6 

 const navigator = await Navigator.current()

// the     navigator.isStackRoot is undefine and navigator.isRoot is define
    navigator.isStackRoot().then((isRoot) => {

    })

**Comment by treemore** [comment]
Finally, we confirmed that this only happens on the ios platform.

**Comment by listenzz** [comment]
It's strange, Their code is same.
