### ISSUE TITLE
Android 点击push的路由的当前page内的图片会消失一下下

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#121]

**Comment by listenzz** [comment]
明显吗？这是 Image 组件底层的工作机制。

**Comment by listenzz** [comment]
https://github.com/facebook/fresco/issues/1841

**Comment by listenzz** [comment]
推荐使用 [FastImage](https://github.com/DylanVann/react-native-fast-image)
