### ISSUE TITLE
Bottom Tabs without title?

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/react-native-navigation-hybrid#123]
Is it possible to disable the titles on the bottom tabs without using a custom bottom bar?
I'm trying to accomplish something like this which i already have on react-native-navigation v2 but the performance and limitations aren't exactly satisfying.

![tabs](https://user-images.githubusercontent.com/3690196/60398915-27646e80-9b90-11e9-87a4-b8ca251d0a61.jpg)

**Comment by listenzz** [comment]
If we don't provide title, the native bottom bar look not so good.

<img width="374" alt="屏幕快照 2019-07-01 上午9 25 26" src="https://user-images.githubusercontent.com/4386370/60405394-73400380-9be2-11e9-8ad7-54453952b708.png">

So, it isn't possible to disable the titles without using a custom bottom bar.

**Comment by 8BallBomBom** [comment]
Pretty much the result i got when messing with the playground app.
When using react-native-navigation and other libraries if you don't set titles for the tabs then they tend to just remove the extra space.

Would it be possible to have this as a future feature?

**Comment by listenzz** [comment]
[Custom tab bar](https://github.com/listenzz/react-native-navigation-hybrid/blob/master/doc/custom-tabbar.md) is easy, but Modifying the default behavior of native components is difficult and the workload is huge, I don't want to add this feature. 

Sorry.

**Comment by 8BallBomBom** [comment]
Ahh no worries, i was assuming things were by the [material design](https://material.io/design/components/bottom-navigation.html) bottom tab bar standards which usually includes that ability.

Would you be open to pull requests?
