### ISSUE TITLE
Tab animations?

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/react-native-navigation-hybrid#124]
Hey there.

Is there any native way currently to implement something like a fade in animation for when tabs are being changed initially? Instead of the loading flash, the gap can be filled with a fade in effect.

**Comment by listenzz** [comment]
This is where we want to optimize, we will try

**Comment by 8BallBomBom** [comment]
Thanks for the latest commit, the fade animations are great :)
Would it be possible to also have an option to make fading happen every tab switch instead of just on initial load?

**Comment by listenzz** [comment]
We put this feature on the low priority queue.

**Comment by 8BallBomBom** [comment]
Also found another issue relating to Animations, unsure exactly what is going on but it would appear when the app first opens, some of the pushed screen transitions can be a little choppy, but then if i reload the app everything seems to start working smoothly.

**Comment by 8BallBomBom** [comment]
I haven't tried the app with a production build yet.
