### ISSUE TITLE
Running application called more than once? [custom tabs]

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/react-native-navigation-hybrid#125]
I'm unsure if this will cause any issues but i noticed if your initial navigation stack is set to use custom tabs then you'll see running application twice in the logs for the tabs component before everything else loads.
Using the native navigation doesn't seem to experience the issue at all.

**Comment by listenzz** [comment]
When we pass props from native to react, application will run again, if you switch tab or change the props of the TabBar, you will see it run again.

**Comment by 8BallBomBom** [comment]
No worries just checking as i was unsure if that was something not working as expected.
