### ISSUE TITLE
(Orientation Change + Header Size) Issues

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/react-native-navigation-hybrid#127]
From what i've seen, if your in landscape mode and a screen gets pushed, the pushed screens header size gets a tiny bit larger or smaller vs the header size in portrait mode.

Also there seems to be an issue where the tab bar doesn't update layouts when changing orientations, a good example is if you start the app in landscape mode with 5 tabs but then change to portrait, you'll only see 3 tabs.

**Comment by 8BallBomBom** [comment]
I have also noticed the unselectedIcon option for the tab bar doesn't seem to work.

**Comment by listenzz** [comment]
Will fix `unselectedIcon`

**Comment by 8BallBomBom** [comment]
Seems that also if you have a screen that has been set to hide the topbar then that also makes you draw under the statusbar at least as far as i've observed on android.
Would it be possible to have an option to define if you draw under the statusbar or not?
Currently the way i've fixed it is just by using the react-native statusbar component on them screens.

**Comment by listenzz** [comment]
This behavior is consistent on both platforms. In this case, we will reserve the padding of the status bar height. We do not intend to provide option to define draw under  the status bar or not, because this requirement  is rare, the cost for adaptation is not so cheap.

**Comment by listenzz** [comment]
> From what i've seen, if your in landscape mode and a screen gets pushed, the pushed screens header size gets a tiny bit larger or smaller vs the header size in portrait mode.

![Screenshot_1563634749](https://user-images.githubusercontent.com/4386370/61580229-0dd89600-ab42-11e9-9150-1d5cffeb8510.png)


I can't reproduce this issue

**Comment by listenzz** [comment]
> Also there seems to be an issue where the tab bar doesn't update layouts when changing orientations, a good example is if you start the app in landscape mode with 5 tabs but then change to portrait, you'll only see 3 tabs.


![Screenshot_1563635026](https://user-images.githubusercontent.com/4386370/61580282-a707ac80-ab42-11e9-9dcf-fd4203e34751.png)

With native TabBar，it seems no that issue.

**Comment by 8BallBomBom** [comment]
Are you testing on a physical device or emulated?
I can provide pictures from my device.

**Comment by listenzz** [comment]
emulated

**Comment by 8BallBomBom** [comment]
I have changed the topbar and status bar colours from white so you can see the issue easier.

Pretty much if you start the app in landscape mode then the topbar height is different, which then translates over to portrait aswell, you can see the effect easier with pushed screens.
As for the bottom tabs, the issue still remains even with the latest master branch version.

Starting the app initially in portrait, you can see the tabs are even spaced and the topbar is a set size.
![Screenshot_20190721-001418_Stumble ](https://user-images.githubusercontent.com/3690196/61581124-cf94a400-ab4c-11e9-95b0-f232244e39e1.jpg)

I then change over to landscape and the topbar size remains the same as it seems but the tabs are now bunched up instead of expanding to the layout width.
![Screenshot_20190721-001425_Stumble ](https://user-images.githubusercontent.com/3690196/61581129-e20edd80-ab4c-11e9-8c2c-755d157b6f2b.jpg)

If i now do the opposite, start the app initially in landscape i see this, the tabs have expanded to the width and the height of the topbar is different.
![Screenshot_20190721-001356_Stumble ](https://user-images.githubusercontent.com/3690196/61581134-fbb02500-ab4c-11e9-8223-1c2b5a254802.jpg)

I then change over to portrait and you get this, the tabs have not adapted to the layout and the topbar height is still different to what you'd expect.
![Screenshot_20190721-001405_Stumble ](https://user-images.githubusercontent.com/3690196/61581148-1b474d80-ab4d-11e9-8b17-b2227d6d47d9.jpg)

**Comment by 8BallBomBom** [comment]
Tested on a Samsung Galaxy S7 Edge along with a Galaxy Tab A10.
