### ISSUE TITLE
纠结于react-navigation和您这个库，能说下您的优势有哪些吗？感谢

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#128]

**Comment by listenzz** [comment]
如果之前没使用过 react-navigation 的话，可以先使用 react-navigation。如果对它不满意，可以再试试本库。

react-navigation 是纯 js 代码写的，是通过 view 动画进行转场，局限于 view。本库是使用原生转场组件进行转场，一个页面就对应着原生的一个控制器，效果和原生相差无几。在 iOS 上的效果就和原生一样。另外对状态栏、导航栏有比较好的控制，本库可以把一个界面当 modal 显示，不会像官方 modal 那样会有状态栏等问题。

本库最大的优点就是 RN 页面可以和原生页面共享路由，可以很方便地从一个原生页面跳转到一个 RN 页面，反过来也一样，当原生页面和 RN 页面混杂在一起时，很难看出哪些是原生页面，哪些是 RN 页面。

**Comment by danna88** [comment]
嗯嗯，非常感谢您的解答，我之前用过react-navigation3.0，当时配合着RN0.59，由于没有使用自带的header，自定义的header，感觉没有原生的效果，但是自带的header在和页面内部进行数据交互的时候很麻烦。

**Comment by danna88** [comment]
嗯嗯，明白了，非常感谢您的解答，我之前用过react-navigation3.0，当时配合着RN0.59，由于自带的header在和页面内部进行数据交互的时候很麻烦，所以没有使用自带的header，而用的自定义的header，感觉没有原生的效果。

另外之前那个APP有即时通信，网络差的时候会不断重连，就会导致跳转卡顿，所以想找找是否有更好的导航解决方案。

我会试试这个库的，看看效果，感谢。
