### ISSUE TITLE
RN0.60.3，引入这个之后，编译报错呢

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#129]
![微信截图_20190719095519](https://user-images.githubusercontent.com/6461710/61503747-7a04ae00-aa0b-11e9-876b-4bf8efb4f0be.png)
![微信截图_20190719095532](https://user-images.githubusercontent.com/6461710/61503750-7b35db00-aa0b-11e9-8e63-caa232c14129.png)
都是乱码和错误，麻烦看下呢？

**Comment by danna88** [comment]
看了下，具体报的这个，程序包android.support.annotation不存在

**Comment by listenzz** [comment]
你好，

这个库目前还没有对 RN 0.60 做兼容，建议使用 0.59 版本

**Comment by danna88** [comment]
是因为我的项目启用了Androidx，我已经全部改完了。希望可以兼容下。

**Comment by listenzz** [comment]
<img width="306" alt="屏幕快照 2019-07-20 下午6 36 40" src="https://user-images.githubusercontent.com/4386370/61577691-76614c00-ab1d-11e9-86fe-8244ba0ebc10.png">

已经兼容 RN 0.60

https://github.com/listenzz/react-native-navigation-hybrid/blob/androidx/doc/integration-react.md

**Comment by listenzz** [comment]
如何和 RN 0.60 集成，可以参考以下项目：

https://github.com/listenzz/react-native-navigation-hybrid-rn60
