### ISSUE TITLE
似乎不支持自定义 切换动画？

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#13]
没见说明里有提到 是否支持？比如安卓的和苹果我想都从右到往左的打开页面

**Comment by listenzz** [comment]
现在它们都是从右往左打开页面

Android 如果需要自定义动画，直接在自己的项目中，使用和本库同名的动画文件就可以覆盖默认的效果。

https://github.com/listenzz/AndroidNavigation/tree/master/navigation/src/main/res/anim

iOS 不支持自定义动画

**Comment by yunuo-tech** [comment]
OK，多谢
