### ISSUE TITLE
这个真的没写反吗

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#133]
![image](https://user-images.githubusercontent.com/5960864/62124484-f006f000-b2fc-11e9-93c1-83dd969ec7a3.png)
怎么大于0.60反而要用旧版？

**Comment by listenzz** [comment]
没有

**Comment by listenzz** [comment]
没有

**Comment by listenzz** [comment]
因为我们在用新的，新的就是 0.16.2

**Comment by yunuo-tech** [comment]
但是您写的这个 这不是 大于0.60的话用0.15.2  小于0.60的话用0.16.2 的意思吗？

**Comment by listenzz** [comment]
@yunuo-tech 是的啊，0.15.2 是支持 0.60 的版本，0.16.2 是支持 0.60 以下的版本，因为我们还在用 0.59 的版本，所以0.16.x 是我们主要维护的版本，😄

**Comment by yunuo-tech** [comment]
> @yunuo-tech 是的啊，0.15.2 是支持 0.60 的版本，0.16.2 是支持 0.60 以下的版本，因为我们还在用 0.59 的版本，所以0.16.x 是我们主要维护的版本，😄

好吧，还可以这样。别的库都是搞个高版本的来支持0.60，你们反向操作。可以可以~😅

**Comment by listenzz** [comment]
你们迁移到 0.60 了么

**Comment by yunuo-tech** [comment]
@listenzz 这不今天准备迁移呢，才看到你写的说明😄

**Comment by listenzz** [comment]
版本已经修正
