### ISSUE TITLE
关于DeepLink的问题

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#134]
app必须是未启动状态才能打开指定页面
如果是启动状态，调用的时候只会唤醒 app，而不能打开指定页面。
这是什么原因？有什么解决办法吗

**Comment by listenzz** [comment]
经过测试 playground 这个项目，发现一切正常。

**Comment by listenzz** [comment]
清理 BUG，有问题重新提 issue
