### ISSUE TITLE
setRoot里面，screen配置了props，目标页面怎么拿到props？

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#137]
设置了如下代码：
Navigator.setRoot({
    stack: {
      children: [
        {screen: {moduleName: routesName.Login, props: {a:'test'},}},
      ],
    },
  });

请问，在Login中，怎么拿到a呢？
文档中没看到说明

**Comment by listenzz** [comment]
在 Login 中，如果无法通过 this.props.a 拿到 a，那么这是个 bug
