### ISSUE TITLE
与某些和RN无关的原生activity的交互可以用此库实现吗？

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#138]
我现在需要集成一个SDK，里面有些带界面的接口，如扫码activity，我能通过这个库方便地进行交互吗？

这个SDK也是自己开发，但是除了自己用之外，也需要提供给第三方用，所以不能和RN有关系。

这种情况，我们也可以用这个库来组织路由吗？

**Comment by listenzz** [comment]
可以。

带界面的接口放到一个 AFragment 中，然后 Activity 使用该 AFragment 作为界面，当和本库集成时，创建一个 BFragment 继承 HybridFragment，然后 BFragment 通过子 Fragment 的方式使用 AFragment 作为界面。

**Comment by danna88** [comment]
我理解的就是，就相当于写一个中间层来启动目标页，是吧

**Comment by listenzz** [comment]
是的
