### ISSUE TITLE
有时rightBarButtonItem并非只有一个

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#14]
很多 app 设计时右侧按钮会有两个，这个时候 react-native-navigation-hybrid就无法满足需求了
左侧有时候也会有这需求，只不过比右边的出现几率小很多。
底层是不是该判断下，如果是数组 就循环显示出来，如果是对象，就只显示一个
![wechatimg49](https://user-images.githubusercontent.com/5960864/38292842-d5c449a6-3817-11e8-9da7-a1ea71708947.jpeg)

**Comment by listenzz** [comment]
考虑支持多个左右按钮

其实现时通过自定义标题栏，也可以做到，参考 playground 中 TopBarTitleView.js 这个文件

**Comment by listenzz** [comment]
0.4.28 开始支持多个按钮，现已发布
