### ISSUE TITLE
tab的icon和unselectedIcon同时设置，有问题

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#140]
如下：
tabItem: {
      title: '应用',
      unselectedIcon: {uri: fontUri({fontFamily: fontFamilys.Iconfont, name: iconName.home, size: iconSize.iconS24})},
      icon: Image.resolveAssetSource(Images.homeHover),
      hideTabBarWhenPush: true,
    },

unselectedIcon用的是iconfont，icon用的是图片，会出现icon显示不出来的问题

**Comment by listenzz** [comment]
当同时设置 icon 和 unselectedIcon 时，图片不会被染色，显示不出来是因为 unselectedIcon 的颜色和 BottomBar 的颜色是一样的。

**Comment by danna88** [comment]
我这边unselectedIcon 的颜色是灰色，tabBarColor 的颜色是默认的白色，不一样啊

**Comment by listenzz** [comment]
iconfont 的颜色默认就是白的

**Comment by danna88** [comment]
难道`font://${fontFamily}/${glyph}/${size}/${color}`;里的color是不生效的吗，我设置了颜色

**Comment by danna88** [comment]
哦，前面说了，同时设置不会着色，所以color失效了？

**Comment by listenzz** [comment]
> 哦，前面说了，同时设置不会着色，所以color失效了？

是的
