### ISSUE TITLE
由于服务器慢，无意发现一个问题，使用this.props.navigator.push，没有进入到预期的页面

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#141]
你好，我目前遇到个这个问题
我的场景是这样的：

登录之后进入首页，在首页会检测某个状态，false的时候，会弹出一个提示框，然后进入后续流程

现在的问题是：
1、进入首页后，由于服务器响应很慢，导致用户进入后可以点击任意其他tab页，如tabB
2、隔了一会儿，弹出阻塞式提示框，走完了一系列流程后，在首页处理返回结果，此时会使用this.props.navigator.push（）到指定页面，但是结果却跑到了第一步的tabB上了

是什么原因呢？这种情况，我该如何处理呢？ 是在处理跳转过程中，处理路由栈，还是监听每个tab的点击事件？

**Comment by listenzz** [comment]
这种情况是出现在哪个平台呢？

可以像下面那样解决

this.props.navigator.switchTab(0)
const navigator = await Navigator.current()
navigator.push()

**Comment by danna88** [comment]
在Android平台上发现的，iOS暂时还未测试

**Comment by listenzz** [comment]
fixed
