### ISSUE TITLE
请问多次点击导航栏上的按钮会多次触发，怎么处理呢？

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#146]
比如按钮是push到某个页面，连续多次点击就会跳很多次，如果用debounce来处理，那所有的地方都得一个个处理，有没有更好的办法？

**Comment by listenzz** [comment]
主要是为了拦截导航操作吗？

```js
Navigator.setInterceptor()
```
如果跳转同一个页面过快，就拦截它

**Comment by danna88** [comment]
> 主要是为了拦截导航操作吗？
> 
> ```js
> Navigator.setInterceptor()
> ```
> 
> 如果跳转同一个页面过快，就拦截它

是的，就是我连续点击3次就会跳转3次，拦截的话，目前还是得一个个页面处理吧？

**Comment by listenzz** [comment]
判断 to 这个参数是否重复出现得太快，就返回 true 拦截，不需要一个个页面处理

`Navigator.setInterceptor(action, from, to, extras)`
