### ISSUE TITLE
能否写个结合 dva.js 的例子？

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#15]
之前一直在用react-navigation，不过在低端安卓机子上反应总有点慢半拍，
这几天对比了下 react-native-navigation-hybrid和react-native-navigation，
决定新项目还是选择用react-native-navigation-hybrid，但是尝试结合 dva.js 来使用总是弄不成功，能否在playground中写个结合的例子？

https://github.com/nihgwu/react-native-dva-starter  这个是react-navigation和 dva 结合的例子

**Comment by listenzz** [comment]
https://github.com/listenzz/react-native-dva-starter

移除了路由

**Comment by yunuo-tech** [comment]
@listenzz 好的，万分感谢！
