### ISSUE TITLE
deeplink，目标页拿不到参数

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#151]
RN版本：0.61.5

根据demo项目和文档，开启了deeplink，能够打开目标页，但是无法获取到参数。
部分配置如下：
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="aaa" android:host="bbb"/>
            </intent-filter>

ReactRegistry.registerComponent(routesName.Login, () => LoginScreen, {
    path: 'login/:appId',
  });

在控制台输入：
>adb shell am start -W -a android.intent.action.VIEW -d "aaa://bbb/login/testapp"

打开了login页面，但是props.appId始终是undefined

**Comment by listenzz** [comment]
可以提供一个复现此问题的 demo，使用 [react-native-create-app]https://github.com/listenzz/react-native-create-app 可以快速创建基于本库的 app

**Comment by danna88** [comment]
刚刚整好了demo,也是空的

**Comment by listenzz** [comment]
demo 发给我

**Comment by danna88** [comment]
邮件吗？

**Comment by listenzz** [comment]
是的

**Comment by danna88** [comment]
已发

**Comment by listenzz** [comment]
少了激活的步骤

```js
Navigator.setRootLayoutUpdateListener(
  () => {
    router.inactivate()
  },
  () => {
    //const prefix = Platform.OS == 'android' ? 'hbd://hbd/' : 'hbd://'
    router.activate('aaa://')
  },
)

Navigator.setRoot({
  stack: {
    children: [{ screen: { moduleName: 'Home' } }],
  },
})

```

Android 中配置成下面这个样子

```xml
<activity
			android:launchMode="singleTask"
			android:name=".MainActivity"
			android:label="@string/app_name"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
			android:windowSoftInputMode="adjustResize">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="aaa" />
			</intent-filter>
		</activity>
```

添加 android:launchMode="singleTask" 

移除 host 和 iOS 保持一致

**Comment by danna88** [comment]
哦，我在项目中是激活了得，demo里忘了加，但是也能跳到对应的界面？ 我试试明天加那句代码看看

**Comment by danna88** [comment]
谢谢，添加android:launchMode="singleTask" 就对了，这是为什么呀？

**Comment by listenzz** [comment]
因为 RN 是单 Activity 应用
