### ISSUE TITLE
Onesignal

### ISSUE THREAD

**Issue by khalisafkari** [listenzz/react-native-navigation-hybrid#152]
I want to use your project in my react native application because I see it easier than react native navigation, but I am confused how to integrate it with onesignal,Which requires using launchMode = "singleTop" while you explain using lauchMode = 'singleTask' in order to deeplink

**Comment by khalisafkari** [comment]
Sorry my English is too bad

**Comment by listenzz** [comment]
It seems that  we could use `singleTask` instead of `singleTop` with Onesignal.

 It seems  everything is OK  if you use  `singleTop`  with this lib.
