### ISSUE TITLE
support deep link with query string?

### ISSUE THREAD

**Issue by futurist** [listenzz/react-native-navigation-hybrid#153]
Can support deep link with query string like below link example:

```
example://theme/colors?textColor=<text_color>
```

So the need is `routeConfig` can have a `query` object beside  the `paramNames`

**PR example:**
https://github.com/react-navigation/react-navigation/pull/510/files

**Lib example:**
https://github.com/Starotitorov/react-native-deep-link

**Article example:**
https://medium.com/the-react-native-log/handle-deep-links-in-react-native-apps-b22055149b3a

**Comment by listenzz** [comment]
We will try.

**Comment by listenzz** [comment]
support it since version 0.23.0
