### ISSUE TITLE
自定义的头部module可以动态设置样式吗

### ISSUE THREAD

**Issue by YangfanY** [listenzz/react-native-navigation-hybrid#155]

**Comment by listenzz** [comment]
当成普通的 React 组件处理就好，动态改变样式应该不成问题

**Comment by YangfanY** [comment]
> 当成普通的 React 组件处理就好，动态改变样式应该不成问题

我需要在FaltList滚动时改变titleItem的module的一些样式，但是顶部module只会渲染一次，无法动态改变。

**Comment by listenzz** [comment]
你好，是可以的。

1. 在 TitileItemModule 的 onComponentDidMount 生命周期函数，或构造函数中，调用 `this.props.navigator.setPrames` 设置一个回调函数来监听 FlatList 的滚动

2.  在处理 FlatList 滚动时，通过 `this.props.navigator.state` 来获取第一步设置的函数（注意非空判断），调用它即可。

**Comment by YangfanY** [comment]
> 你好，是可以的。
> 
> 1. 在 TitileItemModule 的 onComponentDidMount 生命周期函数，或构造函数中，调用 `this.props.navigator.setParams` 设置一个回调函数来监听 FlatList 的滚动
> 2. 在处理 FlatList 滚动时，通过 `this.props.navigator.state.params` 来获取第一步设置的函数（注意非空判断），调用它即可。

好的，感谢，我去试下😂
