### ISSUE TITLE
请问有动态隐藏tabbar的方法吗

### ISSUE THREAD

**Issue by YangfanY** [listenzz/react-native-navigation-hybrid#157]

**Comment by listenzz** [comment]
没有，只能通过根页面的 tabItem 来设置 push 的时候要不要隐藏 TabBar

```js
    tabItem: {
      hideTabBarWhenPush: true,
    },
```

**Comment by YangfanY** [comment]
> 没有，只能通过根页面的 tabItem 来设置 push 的时候要不要隐藏 TabBar
> 
> ```js
>     tabItem: {
>       hideTabBarWhenPush: true,
>     },
> ```

我现在使用antd的modal不能从底部唤起， 会被tabbar顶上去，有什么好的解决方法吗。。

**Comment by listenzz** [comment]
请使用本库提供的 showModal 路由方法。

**Comment by YangfanY** [comment]
> 请使用本库提供的 showModal 路由方法。

尝试过，无法遮盖tabbar，只有rn的modal可以完全覆盖，但是无法满足需求。。

**Comment by listenzz** [comment]
不是很明白你说的遮盖 tabbar 是什么意思

**Comment by YangfanY** [comment]
> 不是很明白你说的遮盖 tabbar 是什么意思

showModal出来的modal无法覆盖底部的导航栏，我想知道的是 怎么可以覆盖导航栏😂

**Comment by listenzz** [comment]
请上图

**Comment by YangfanY** [comment]
![image](https://user-images.githubusercontent.com/31607682/71477451-26ea1f00-2825-11ea-8f51-4e2b73d7696e.png)
如图，modal无法遮住tabbar

**Comment by listenzz** [comment]
showModal 出来的界面，本质是个 window，不可能盖不住底下的 TabBar

**Comment by YangfanY** [comment]
> showModal 出来的界面，本质是个 window，不可能盖不住底下的 TabBar

使用了showModal方法，解决问题了，感谢
