### ISSUE TITLE
如何反向传值？

### ISSUE THREAD

**Issue by 593980284** [listenzz/react-native-navigation-hybrid#159]
this.props.navigator.push(
        'SearchAddress',
        //传入方法
        {  callBack: ({ name }) => {
            console.log(name)
          }
        }

调用的是报错
class SearchAddress。。。。。{
    this.props.callBack();
}

**Comment by listenzz** [comment]
暂不支持通过 props 参数传递函数，想要反向传值，如果用的是 present 或 showModal，await 即可，如果用的是 push，需要实现 `onComponentResult` 方法，SearchAddress 在返回前通过 this.props.navigator.setResult 设置要返回的结果。setResult 同样也只能传递 JSON

**Comment by 593980284** [comment]
谢谢🙏

**Comment by 593980284** [comment]
onComponentResult = (data)=>{
    alert(JSON.stringify(data));
  }

class SearchAddress。。。。。{
   this.navigator.setResult({name: 111})
    this.navigator.pop()
}

JSON value '{
    name = 11;
}' of type NSMutableDictionary cannot be converted to NSNumber

+[RCTConvert NSNumber:]
    RCTConvert.m:57
+[RCTConvert NSInteger:]
__41-[RCTModuleMethod processMethodSignature]_block_invoke_8
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by listenzz** [comment]
setResult 需要两个参数，第一个是个 number，表示结果码，第二个才是要返回的结果

onComponentResult 有三个参数，第一个是 number, 表示请求码，第二个是 number,  就是返回来的结果码，第三个 object 是返回来的果

```ts
setResult<T = any>(resultCode: number, data: T = {} as T): void
```

```ts
onComponentResult(requestCode: number, resultCode: number, data: T)
```

**Comment by listenzz** [comment]
结果还可以这么接，我自己都忘了
```js
const [resultCode, data] = await this.props.navigator.push('Navigation', props)
```
