### ISSUE TITLE
若干个 问题

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#16]
1.如果 icon 用的是图片，如何控制这个 icon 的大小？ 现在tabItem的图片不知道为什么，显示超大，如图所示
2.如果leftBarButtonItem的 icon 也设置了图片，标题会消失，如上图所示：
![image](https://user-images.githubusercontent.com/5960864/38736345-51b37a80-3f5e-11e8-9631-b81e84f5b5a1.png)
3.leftBarButtonItem中的按钮 如果是第一次点击，会有个很明显的点击效果，但是之后再点击，不知道为什么这个点击效果就很不明显了。如下图所示。
![4 -13-2018 21-08-07](https://user-images.githubusercontent.com/5960864/38736495-d02bf7b6-3f5e-11e8-8969-1c40f4309832.gif)
4.横屏后 头部和尾部与竖屏的时候表现似乎不一致？ 如下图所示

![image](https://user-images.githubusercontent.com/5960864/38736599-248caa8a-3f5f-11e8-9159-7dfe2818d991.png)

以下是代码

```
    static navigationItem = {
        titleItem: {
            title: 'RN navigation',
        },

        leftBarButtonItem: {
            title: 'SETTING',
            action: navigation => {
                console.info('setting button is clicked.');
            },
            icon: Image.resolveAssetSource(require('../images/house.png')),
        },

        topBarColor: '#FF0000',
        tabItem: {
            title: '组件',
            icon: Image.resolveAssetSource(require('../images/house.png')),
            // inactiveIcon: { uri: 'blue_solid', scale: PixelRatio.get() },
            hideTabBarWhenPush: true,
        },
    };
```

**Comment by listenzz** [comment]
这张图片有 512*512 那么大，所以特别大。
换张小的就可以了，一般需要有两个尺寸的图片，以@2x 和@3x 区分

**Comment by listenzz** [comment]
横屏的时候会隐藏状态栏
