### ISSUE TITLE
[Android] App Loading Issue

### ISSUE THREAD

**Issue by 8BallBomBom** [listenzz/react-native-navigation-hybrid#161]
Came across a random issue that seems to happen very rarely but you can trigger the bug by simply launching an app using this module but then instantly pushing the power button.
Pretty much what happens is you get these 2 errors and the app never loads properly.
You end up with a blank screen.

```
W/unknown:ReactNative: no layout to set when create main component
W/unknown:ReactNative: have no active activity or react module was not registered, schedule pending root
```
No idea if the same issue occurs on iOS.

**Comment by 8BallBomBom** [comment]
Seems [this part of the code](https://github.com/listenzz/react-native-navigation-hybrid/blob/7db378b8038a1eaa851e2ea938c6703ac7b57f03/android/src/main/java/com/navigationhybrid/ReactAppCompatActivity.java#L170) that should run on resume doesn't actually run.

**Comment by 8BallBomBom** [comment]
Alrighty after some more testing it seems the simple screens i had do load but as they were just basic screens with text for testing and as the text was white and the default app style is loading as pure white i couldn't tell as such.
So the issue is, if the app goes into the paused state instantly after opening then the call to **Garden.setStyle** doesn't get applied when the app resumes.
A simple solution that seems to work is to just stick styles in each component via the static navigationItem variable as they would then apply as the component loads.

Another solution would be to save any styles sent to the **Garden** if the app is not fully running properly then apply the styles on resume.

**Comment by 8BallBomBom** [comment]
After a bit of snooping about, a solution like what React Native Navigation has should do the job.
Pretty much if we [emit an event that the app has launched](https://github.com/listenzz/react-native-navigation-hybrid/blob/7db378b8038a1eaa851e2ea938c6703ac7b57f03/android/src/main/java/com/navigationhybrid/ReactBridgeManager.java#L73) and is ready to start setting styles and setting a root when the react context initialises then it should fix the problem.
That does mean wrapping **Garden.setStyle** and **Navigation.setRoot** within the event function.

**Comment by 8BallBomBom** [comment]
Alrighty scratch that, doesn't seem to help much, it comes down to the Garden.setStyle function needing some changes to fix the issue as it would appear that it might run but not actually set the styles properly if the app is instantly paused then resumed shortly after.

In general it isn't a big deal but if you have for example multiwindow support on your app or you quickly switch between apps on launching then it can become an issue.

**Comment by listenzz** [comment]
Try 0.18.5

**Comment by 8BallBomBom** [comment]
Definitely beats what i slapped together, thanks, that fixed the issue :)
