### ISSUE TITLE
Now working in react native 0.62.0

### ISSUE THREAD

**Issue by khalisafkari** [listenzz/react-native-navigation-hybrid#164]
I upgraded react native 61.5 to 62, but the application crashed immediately when opened

**Comment by dntzee** [comment]
EN:
add implementation 'androidx.legacy:legacy-support-v4:1.0.0' in your build.gradle
CN:
android/app/build.gradle
添加
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
即可
