### ISSUE TITLE
关于deeplink的两个问题

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#165]
1、在playground项目测试的：
在设置UI层级的时候，因为往往会写一个screen来根据状态跳到不同页面，所以是类似这样设置的
Navigator.setRoot({screen: {moduleName: 'Navigation'}},);
输入命令：adb shell am start -W -a android.intent.action.VIEW -d "hbd://topBarAlpha/0.5/#FFFFFF"
此时deeplink只能启动APP，无法跳转到指定页面
**只能这样设置UI层级就行，疑惑：**
Navigator.setRoot({
    stack: {
        children: [{screen: {moduleName: 'Navigation'}}],
    },
})

2、**如果参数是url，就无法解析这个参数**，导致无法跳转
如：adb shell am start -W -a android.intent.action.VIEW -d "hbd://topBarColor/http://baidu.com"

以上，麻烦了。

**Comment by danna88** [comment]
第二个问题，我先把URL做encode，然后用decodeURIComponent处理就可以

**Comment by listenzz** [comment]
第一个问题：deeplink 默认会做 push 操作，如果没有 stack 的话，该操作就会取消，可以通过配置  mode 参数来改变默认操作。

如果需要通过一个screen来根据状态跳到不同页面，那么跳到指定页面后再激活路由。

**Comment by danna88** [comment]
嗯，我就设置成stack吧，没啥影响。
