### ISSUE TITLE
关于inactiveIcon的两点疑问

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#17]
1.从字面上理解，设置inactiveIcon后应该是在当前tab时显示该图标，但是现在情况正好相反。
比如下图，默认是在组件tab上，应该是实心却显示虚的，但是切换到布局tab后，组件反而成实心，布局成虚的图标了。

![4 -14-2018 14-08-24](https://user-images.githubusercontent.com/5960864/38765064-56731c8a-3fed-11e8-9435-75aba7a82bfd.gif)

2.切换 tab 时 底部的字颜色变了，但是图标的颜色并没有变，能否让图标也跟着变化。或者fontUri这个函数增加一个改变字体颜色的参数，但我感觉最好能统一变化。

**Comment by yunuo-tech** [comment]
对了，第二个问题，如果不设置inactiveIcon的话就正常了

**Comment by listenzz** [comment]
icon 表示选中效果，inactiveIcon 表示未选中效果。

通过 Garden.setStyle 设置以下选项来控制 **文字*** 的颜色，当只设置 icon 时，也对 icon 生效
bottomBarButtonItemActiveColor: String // 底部 TabBarItem 选中效果
bottomBarButtonItemInactiveColor: String // 底部 TabBarItem 未选中效果

**Comment by yunuo-tech** [comment]
bottomBarButtonItemActiveColor: String // 底部 TabBarItem 选中效果
bottomBarButtonItemInactiveColor: String // 底部 TabBarItem 未选中效果

这个有设置，但是并不起作用，只对文字有效果 对 icon 无效

**Comment by yunuo-tech** [comment]
icon 表示选中效果，inactiveIcon 表示未选中效果。

这两个参数真的会让人误解造成使用方法错误， 
建议更换为
icon 表示未选中效果，
inactiveIcon或selectedIcon 表示已选中效果。

**Comment by listenzz** [comment]
inactive 表示不活跃，注意前面的 in

**Comment by yunuo-tech** [comment]
`inactive 表示不活跃，注意前面的 in`
替我英语老师感谢你~ 哈哈，这个我还真不知道，我以为『在活跃』的意思。。。
建议后面增加同时用icon 和 inactiveIcon时能对图标颜色生效的参数，因为有时候会有这个需求。
