### ISSUE TITLE
最新版useVisibleEffect无法正确使用了

### ISSUE THREAD

**Issue by danna88** [listenzz/react-native-navigation-hybrid#175]
0.27.4版本，useVisibleEffect无法捕获到很多情况下的页面显示与隐藏，比如，退后后台后回到页面。

**Comment by listenzz** [comment]
@danna88 如果只是*退后后台后回到页面*这种情况，那么是正常设置。

想要监听 app 从后台进入前台的情况，可以使用 https://github.com/react-native-community/hooks#useappstate

**Comment by danna88** [comment]
哦，之前的版本也可以监听到，那现在只好分开处理了。

**Comment by listenzz** [comment]
@danna88 之前只能在 Android 平台监听到，现在保持和 iOS 一样
