### ISSUE TITLE
使用MaterialIcons图标IOS报错

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#26]
![2018-05-10 1 48 36](https://user-images.githubusercontent.com/30352961/39833542-87462094-53f4-11e8-9d1d-a5173829e8c6.png)

`
icon: {uri: FontUtil('MaterialIcons', 'explore', 24)},
`

 Android 正常运行，IOS报错，使用MaterialIcons图标

**Comment by listenzz** [comment]
这个问题你解决没？

**Comment by NrqhEIcsRi004** [comment]
没有，只能用FontAwesome字体，想请你喝咖啡。有账号没有？

**Comment by listenzz** [comment]
尝试了其它几个，也可以，就是 MaterialIcons 不可以，我也晕了

```javascript
//icon: { uri: fontUri('EvilIcons', 'clock', 24) },
// icon: { uri: fontUri('Ionicons', 'md-walk', 24) },
icon: { uri: fontUri('MaterialIcons', 'call', 24) },
```
