### ISSUE TITLE
請問可以用連react-native-push-notification一起用嗎？

### ISSUE THREAD

**Issue by seanlau555** [listenzz/react-native-navigation-hybrid#3]
就我所知，大部分的react native app都在用react-native-push-notification，但由於wix/react-native-navigation的android不支持到，必需用另一個wix/react-native-notifiction。可惜，wix/react-native-notifiction應用很差，有很多bugs。所以如果能為react-native的navigation生態做出native的解決方案而又可用到react-native-push-notification就最好喔!!

感謝！

https://github.com/zo0r/react-native-push-notification

**Comment by listenzz** [comment]
暂时未测试是否支持
