### ISSUE TITLE
能否支持 navigation change 事件？

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#30]

**Comment by listenzz** [comment]
能否具体点？

**Comment by NrqhEIcsRi004** [comment]
想统计每个屏幕访问量

**Comment by NrqhEIcsRi004** [comment]
ReactRegistry.registerComponent('Home', () => Home); 
能否使用Home 作为默认的Screen名称
能否在提供获取当前Screen名称方法？

**Comment by listenzz** [comment]
ReactRegistry.registerComponent('Home', () => Home);

Screen.InternalComponent === Home

Screen 只是一个变量名

刚测了下，screenProvider() 返回值正常，请确保使用 0.6.12 以上版本

**Comment by listenzz** [comment]
import { router } from 'react-native-navigation-hybrid';

总是可以通过 router.currentRoute() 来获取当前页面

router.currentRoute().then(result => {
     console.info(result.moduleName);
 });

moduleName 是注册组件时使用的 key, 比如 'Home'

**Comment by listenzz** [comment]
如果使用了 redux 

```javascript
function screenWrapper(screenProvider) {
  const Screen = screenProvider();
  class ScreenWrapper extends Component {
    componentDidMount() {
      // 获取屏幕名称
      const screenName = Screen.InternalComponent.name;
      console.info(`screenName:${screenName}`);
    }

    render() {
      return (
        <Provider store={store}>
          <Screen {...this.props} />
        </Provider>
      );
    }
  }
  return ScreenWrapper;
}
```
打印结果是 screenName:Connect

看来要提供其它方法来获取屏幕名称

**Comment by NrqhEIcsRi004** [comment]
通过事件的方式解决了
