### ISSUE TITLE
能否支持链式操作？

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#32]
await this.props.navigation.pop()
await this.props.navigation.push('A')

**Comment by listenzz** [comment]
像这种先 pop 后 push 的情况，可以用 this.props.navigation.replace('A') 代替

不支持 await

**Comment by NrqhEIcsRi004** [comment]
其实能支持回调也挺好

**Comment by listenzz** [comment]
很难知道原生那边什么时候完成转场，如果没完成转场就 resolve, 就跟没有 await 一样

**Comment by listenzz** [comment]
这个只有在 pop 或 dismiss 时才会调用，而且会在 pop 或 dismiss 之前调用
