### ISSUE TITLE
Android 4.4.4  报错

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#35]
Could not find class 'me.listenzz.navigation.AppUtils$1', referenced from method me.listenzz.navigation.AppUtils.setStatusBarTranslucent

**Comment by NrqhEIcsRi004** [comment]
multiDexEnabled true

**Comment by listenzz** [comment]
有参考这里面的配置吗？5.0 以上和以下的配置是不一样的

https://developer.android.com/studio/build/multidex

**Comment by NrqhEIcsRi004** [comment]
java.lang.IllegalStateException: must call ReactBridgeManager#install first

**Comment by NrqhEIcsRi004** [comment]
有参考https://developer.android.com/studio/build/multidex 但是启动时候报错java.lang.IllegalStateException: must call ReactBridgeManager#install first

**Comment by listenzz** [comment]
看了下我们的项目，像下面这么配，没发现异常

```groovy
dependencies {
    api 'com.android.support:multidex:1.0.1'
}
```

```java
public class App extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        // react native
        SoLoader.init(this, /* native exopackage */ false);
        ReactBridgeManager bridgeManager = ReactBridgeManager.instance;
        bridgeManager.install(getReactNativeHost());
    }

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
}
```

<img width="163" alt="2018-06-19 2 28 33" src="https://user-images.githubusercontent.com/4386370/41580351-370ea4ea-73cd-11e8-9f7c-91c389fdf0d3.png">

**Comment by NrqhEIcsRi004** [comment]
我这边还是有这个错误。。。。
 Could not find class 'me.listenzz.navigation.AppUtils$1', referenced from method me.listenzz.navigation.AppUtils.setStatusBarTranslucent

**Comment by NrqhEIcsRi004** [comment]
也不行，同样的配置下 7.1.1 能正常运行

**Comment by listenzz** [comment]
setStatusBarTranslucent 里面有一个匿名类，但 4.4.4 的版本不应该会执行到那个路径。你能看下你所使用的版本的 setStatusBarTranslucent 这个方法是如何实现的吗？

**Comment by NrqhEIcsRi004** [comment]
使用的是0.7.11

**Comment by NrqhEIcsRi004** [comment]
是不是要发个release 版本号对不上

**Comment by NrqhEIcsRi004** [comment]
源码中的版本号有影响吗？
// api project(':navigation')
   api 'me.listenzz:navigation:1.6.11'

**Comment by listenzz** [comment]
有的，你使用的不是这个版本么？

**Comment by NrqhEIcsRi004** [comment]
是不是没有1.6.11 应该是0.6.11

**Comment by listenzz** [comment]
版本号是对的

**Comment by NrqhEIcsRi004** [comment]
AndroidManifest.xml 文件里面显示android:versionName='0.7.11'

**Comment by listenzz** [comment]
0.7.11 是 com.navigationhybrid 的版本号
1.6.11  是 me.listenzz.navigation 的版本号

**Comment by NrqhEIcsRi004** [comment]
ext {
    minSdkVersion = 16
    targetSdkVersion = 22
    compileSdkVersion = 27
    buildToolsVersion = '27.0.3'
    supportLibraryVersion = '27.1.1'
}
这样配置没有问题吧...

**Comment by treemore** [comment]
我们的项目也出现了这个问题。
我把你的例子项目 https://github.com/listenzz/reading  试了一下。 在4.4.X版本的手机上面同样出现了这个问题。
multiDexEnabled  已经按照文档的要去配置了。

**Comment by treemore** [comment]
multiDexKeepProguard file('multidex-config.pro')
里面加上 -keep class me.listenzz.navigation.** {*;} 也不行。

**Comment by listenzz** [comment]
@treemore reading 这个项目还没达到分包的标准，我刚刚尝试了配置 multiDexEnabled, 打出来的包里面只有一个 dex。 我推了一个新的 commit 到 reading 来演示我是如何配置 multi dex 以及混淆的。
配置好后，通过如下方式打包：

cd reading/android

./gradlew clean assemble

通过以下方式安装 apk 到模拟器 

adb install -r app/build/outputs/apk/release/app-x86-release.apk 

通过以下方式安装 apk 到真机

adb install -r app/build/outputs/apk/release/app-armeabi-v7a-release.apk 

在 4.4.4 系统上均未发现异常

关键修改如下：

![jietu20180628-105632](https://user-images.githubusercontent.com/4386370/42010640-2f5344c6-7ac2-11e8-820a-03444adcbc49.jpg)
![jietu20180628-105721](https://user-images.githubusercontent.com/4386370/42010649-38274c8c-7ac2-11e8-9826-624ca6178cdb.jpg)

![jietu20180628-105554](https://user-images.githubusercontent.com/4386370/42010657-4796f820-7ac2-11e8-9dd1-dd0138d0de55.jpg)

![jietu20180628-105311](https://user-images.githubusercontent.com/4386370/42010670-571395b0-7ac2-11e8-9430-d8507fe7dad2.jpg)

![jietu20180628-105532](https://user-images.githubusercontent.com/4386370/42010674-5d73abca-7ac2-11e8-99da-7315a8460b2a.jpg)

**Comment by listenzz** [comment]
在往 reading 里面塞了几个类库后，终于可以分包了，但是在 nexus5  4.4.4 真机上没发现异常

![jietu20180628-120942](https://user-images.githubusercontent.com/4386370/42012776-6a0695b4-7acc-11e8-92cf-f9ab1d097085.jpg)

[reading.zip](https://github.com/listenzz/react-native-navigation-hybrid/files/2143711/reading.zip)

**Comment by listenzz** [comment]
我在  4.2.x 的模拟器上复现了你们所说的问题，但应用并未崩溃。

![jietu20180628-122615](https://user-images.githubusercontent.com/4386370/42013272-11b0fe7e-7acf-11e8-88d8-37a4842401de.jpg)

![jietu20180628-122657](https://user-images.githubusercontent.com/4386370/42013279-19282e8e-7acf-11e8-8ec3-eb1b4103b4e7.jpg)

![jietu20180628-122724](https://user-images.githubusercontent.com/4386370/42013291-266de944-7acf-11e8-9e4c-ad542268afc8.jpg)

从上面这些截图可以看到，这类错误提示很普遍，所以崩溃的原因很可能是混淆文件没有配置好。

**Comment by treemore** [comment]
不好意思。 逐行定位了一下。 确实不是这个库的问题。
虽然logcat 只有一个报错信息
Could not find class 'me.listenzz.navigation.AppUtils$1', referenced from method me.listenzz.navigation.AppUtils.setStatusBarTranslucent
我们是debug就报错了。混淆是关闭的。
me.listenzz:navigation:1.6.11
me.listenzz:navigation:1.6.1
对应的jar包反编译出来me.listenzz.navigation.AppUtils$1 也都存在。。


耽误你时间了。 还搞了这么详细的回复。 建议你首页上面加个支付宝，请你喝咖啡 。

**Comment by listenzz** [comment]
@treemore 不用客气，请问真正的原因找到没？
