### ISSUE TITLE
关于topbar跟下面的页面遮盖的问题

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#37]
render() {
    const { value, onIncreaseClick } = this.props;
    return (
      <ScrollView >
     </ScrollView>
    );
  }
就是这个scrollview要padding这个tabbar的高度 这个布局只能做成这样还是bug? 不知道我描述的清楚么？

**Comment by listenzz** [comment]
布局就是这样的，请参考 playground 中的处理方式，后续会优化。

**Comment by VictorYuan666** [comment]
好的 谢谢~~

**Comment by listenzz** [comment]
0.8.0 已修正，如果 TopBar 的颜色不带透明度，则不会遮盖页面。
