### ISSUE TITLE
StatusBar.setHidden(true) 时状态栏始终有个色块。

### ISSUE THREAD

**Issue by treemore** [listenzz/react-native-navigation-hybrid#38]
StatusBar.setHidden(true) 生效了，但是状态栏那个位置始终有个色块，正常的状态栏确实隐藏了，下拉一下可以拉下来。
react-native-navigation-hybrid 版本是0.7.14.

android版本有这个问题。 ios 没有

**Comment by treemore** [comment]
以前的某个版本应该没有这个问题的。 
然后也试了一个不用这个路由的项目。
StatusBar.setHidden(true) 没有那个色块。 应该不是react-native的问题。

**Comment by treemore** [comment]
很容易重现。 任何一个安卓手机 StatusBar.setHidden(true)   就能看到状态栏上面的色块了

**Comment by listenzz** [comment]
能否给个图呢？色块和导航栏是一个颜色不？

**Comment by NrqhEIcsRi004** [comment]
好像是路由的问题，如果使用push打开的页面就隐藏不了状态栏。

**Comment by NrqhEIcsRi004** [comment]
在componentDidAppear设置就好了

**Comment by treemore** [comment]
加到componentDidAppear里面生效了。。。

**Comment by NrqhEIcsRi004** [comment]
4.4.4 上面没有隐藏成功...
