### ISSUE TITLE
组件中拿不到this.props.navigation该如何实现页面跳转

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#39]

**Comment by VictorYuan666** [comment]
就是我有个公共的组件并没有注册页面 我如何实现跳转？ 你们的app是如何处理的？

**Comment by listenzz** [comment]
父组件传递进去

**Comment by VictorYuan666** [comment]
react native navigation中使用了 Navigator.push 这种API 感觉这种比较方便点

**Comment by listenzz** [comment]
Navigator.push 需要传递组件 id.  本库也支持类似方式，  Navigator.dispatch(...)，0.8.0 开始支持，还没发版，不过 Playground 这个项目可以体验到了

**Comment by treemore** [comment]
this.props.navigation  这个是不是在master分支上面改名成this.props. navigator 了 ?

**Comment by iloveyumiforever** [comment]
可不可以講一下 Navigator.dispatch 怎用啊，沒文件

**Comment by listenzz** [comment]
以 push 为例：

```javascript
Navigator.dispatch(this.props.sceneId, 'push', { moduleName: 'xxxxx'});
```

**Comment by iloveyumiforever** [comment]
請問這個 this.props.sceneId 是指？
