### ISSUE TITLE
能否补充下Native跳转到RN RN跳转到Native的文档？

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#4]
最好能在playground中写个例子 谢谢~

**Comment by listenzz** [comment]
文档稍后补充，但是 playground 已有例子，在侧边栏那里进去

**Comment by listenzz** [comment]
文档已更新，如有疑问，请及时告知

**Comment by VictorYuan666** [comment]
@listenzz 谢谢~ 我们公司现在想做原生跟RN的混合开发 正在调研看使用哪个路由库 能否留个联系方式？ 方便向您请教下 我是做前端开发的 对原生不太熟

**Comment by listenzz** [comment]
请提供微信号，我加你

**Comment by VictorYuan666** [comment]
17682342576 @listenzz
