### ISSUE TITLE
Android 4.4.4 不能隐藏状态栏

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#41]
https://github.com/listenzz/react-native-navigation-hybrid/issues/38

**Comment by listenzz** [comment]
本库内部有对导航栏进行处理。我试试把配置项打开

**Comment by listenzz** [comment]
隐藏状态栏的功能已经开发完成。感觉在 iPhoneX 上没有隐藏状态栏的必要，所以在该款机器上隐藏状态栏无效？有任何意见？

**Comment by NrqhEIcsRi004** [comment]
能否发个版本？

**Comment by listenzz** [comment]
0.8.0 已发布，主要更新如下：

支持自定义容器和导航

Android 支持侧滑返回

TopBar 不再遮挡内容

支持隐藏状态栏
