### ISSUE TITLE
需要监听页面跳转分析用户的行为路径

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#46]
react navigation中在根视图上有个 onNavigationStateChange，react-native-navigation-hybrid没有根视图实现这个是要注册监听么 有计划实现这个么 https://reactnavigation.org/docs/en/screen-tracking.html

**Comment by listenzz** [comment]
我们有这个：

```
Navigator.setInterceptor((action, from, to, extras) => {
  console.info(`action:${action} from:${from} to:${to}`);
});
```

可以满足部分需求

**Comment by VictorYuan666** [comment]
可以的 够用了 谢谢~

**Comment by VictorYuan666** [comment]
这个可以补充到文档里👍
