### ISSUE TITLE
有些组件需要在根视图上注册 

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#47]
类似于https://github.com/instea/react-native-popup-menu/ 这个组件是不是注册根视图就跟redux的这个例子类似？
function screenWrapper(screenProvider) {
  const Screen = screenProvider();
  return props => (
    <Provider store={store}>
      <Screen {...props} />
    </Provider>
  );
}

ReactRegistry.startRegisterComponent(screenWrapper);

**Comment by listenzz** [comment]
是的，不过这样每个页面都有一个 popup 了，事件需要去重，处理不好会有多个 popup 叠加在一起。
