### ISSUE TITLE
"PopTo Last but one" not work

### ISSUE THREAD

**Issue by michaeldong** [listenzz/react-native-navigation-hybrid#51]
场景：
一个RN页（A) ，之后push一个Native页面(B)，再push一个RN页面(C)。
一共三个页面，因为Native页（B)做push的时候，无法传递popToId给RN页(C)，RN页(C)无法感知。

因此，无法PopTo Last but one.

**Comment by listenzz** [comment]
你好，原生页面在 push 到其它页面的时候，是可以传参的，以 iOS 为例：

从 B 跳到 C

```objc
 HBDViewController *vc = [[HBDReactBridgeManager sharedInstance] controllerWithModuleName:@"C" props:@{ @"popToId": self.props[@"popToId"]} options:nil];
        [self.navigationController pushViewController:vc animated:YES];
```

popToId 是 A（RN） 页面传给 B（原生） 页面的

**Comment by michaeldong** [comment]
👍 我试下去，看起来ok。 谢谢！

**Comment by michaeldong** [comment]
这个场景下，测试通过没问题；

说个场景：
A（Native)  -> B( Native ) -> C (Native) -> D(RN) .

想从D直接回到B的话，需要B把sceneId 传给C 通过popToId 传给D.
建议demo改成这个：
 NSDictionary *prop = nil;
        if(self.props[@"popToId"]) {
            prop = @{@"popToId": self.props[@"popToId"]};
        }
        else {
            prop = @{@"popToId": self.sceneId};
        }
        OneNativeViewController *vc = [[OneNativeViewController alloc] initWithModuleName:@"OneNative" props:prop options:nil];

**Comment by listenzz** [comment]
demo 已改
