### ISSUE TITLE
this.props.garden.setTabBarColor 高度计算好像有问题，如果内容是一个ScrollView，ScrollView高度会不停跳

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#55]

**Comment by listenzz** [comment]
```jsx
<ScrollView
        contentInsetAdjustmentBehavior="never"
        automaticallyAdjustContentInsets={false}
        contentInset={{ top: 0, left: 0, bottom: 0, right: 0 }}
      >
 //...
</ScrollView>
```

**Comment by NrqhEIcsRi004** [comment]
还是会有白色的块，不停闪动，白色的块高度与tabbar一致

**Comment by listenzz** [comment]
tabBar 的颜色是不是透明的？

**Comment by NrqhEIcsRi004** [comment]
不是透明的
![2018-08-22 4 11 32](https://user-images.githubusercontent.com/30352961/44454596-1967c800-a626-11e8-9659-71b1010d28ab.png)

**Comment by listenzz** [comment]
playground 这个项目也有用 scrollview, 没发现你说的那种情况呢

是否可以参考下 playground 的做法？

**Comment by NrqhEIcsRi004** [comment]
就在上面，一直显示着
this.props.garden.setTabBarColor({tabBarColor: '#ffffff'})

**Comment by NrqhEIcsRi004** [comment]
必须先push一个页面再返回才会有

**Comment by listenzz** [comment]
我无法复现这个问题，你可以写个项目来复现这个问题么？

**Comment by NrqhEIcsRi004** [comment]
嗯 好的，我猜测跟设置显示状态栏有关，在返回的时候有执行显示状态栏。在Android设备上面没有这个问题。

**Comment by NrqhEIcsRi004** [comment]
还有我发现另外一个问题，在android设备下执行 setTabBarColor 方法，tab的选择状态会到第一个

**Comment by NrqhEIcsRi004** [comment]
https://github.com/listenzz/react-native-navigation-hybrid/blob/master/ios/NavigationHybrid/React/HBDGardenModule.m#L135
这行代码注释了就好了。。。

**Comment by listenzz** [comment]
是 tabBar 的 translucent 发生变化所致

**Comment by NrqhEIcsRi004** [comment]
后面加一段就好了 [tabBarVC.tabBar setTranslucent:true]

**Comment by listenzz** [comment]
translucent 的值是受 tabBarColor 的值影响，一开始通过 Garden.setStyle 设置一个不透明的 tabBarColor, 后续通过 garden.setTabBarColor 再设置不透明的背景颜色，应该没问题了

**Comment by NrqhEIcsRi004** [comment]
translucent 为yes的场景是可以。 但是那个透明度太低了。 不满足需求。


translucent 的值是受 tabBarColor 的值影响，一开始通过 Garden.setStyle 设置一个不透明的 tabBarColor, 后续通过 garden.setTabBarColor 再设置不透明的背景颜色，应该没问题了

按上面的设置还是不行。

然后我怀疑是不是我加的代码 translucent 没有自动设置好。 我直接在代码里面写死translucent=NO
HBDTabBarController.m
```c

viewDidLoad
self.tabBar.translucent= NO;
```
还是会有个白的。 那个白的应该刚好是tabbar的高度。然后我设置下面的配置。
hideTabBarWhenPush:false

在push 。然后pop 之后，发现那个白块没有了。 还没发现问题出在哪里，我在继续看看。
不行的话我在弄个demo出来重现bug

**Comment by NrqhEIcsRi004** [comment]
另外发现。 如果在push出来的页面里面
```js
this.props.navigation.pop(false)
```
关闭动画也不用有问题。
但是如果用手势关闭那个问题有出现了。  


**Comment by NrqhEIcsRi004** [comment]
已经定位到问题。 应该跟这个库没关系

**Comment by treemore** [comment]
我们换搞换主题也出现了相同的问题.
最后定位是因为调试模式下YellowBox 内部使用了ScrollView 没有加上
 contentInsetAdjustmentBehavior="never"
        automaticallyAdjustContentInsets={false}
        contentInset={{ top: 0, left: 0, bottom: 0, right: 0 }}
引起的
