### ISSUE TITLE
切换主题时部分颜色没有生效

### ISSUE THREAD

**Issue by treemore** [listenzz/react-native-navigation-hybrid#56]
用下面的代码切换了主题,每个主题下面的三个颜色都相同. 发现screenBackgroundColor生效了,  
tabBarItemColor 跟tabBarSelectedItemColor 没有生效
```js
 Garden.setStyle({
                tabBarItemColor: $tabBarItemColor,
                tabBarSelectedItemColor: $tabBarSelectedItemColor,
                screenBackgroundColor: $bgColor
            });
```
看了一下代码,感觉tabBarItemColor  tabBarSelectedItemColor screenBackgroundColor 三个方法  
都会调用, 为什么只有screenBackgroundColor生效了 ? 或者我哪里设置有问题 ?

**Comment by treemore** [comment]
方法应该都调到了.
https://github.com/listenzz/react-native-navigation-hybrid/blob/bf1238455d6c873be5aaf2452483aa09bd0b8573/ios/NavigationHybrid/GlobalStyle.m#L34

**Comment by listenzz** [comment]
当同时设置选中时和未选中时的图片，就不会用这两个颜色来为图片着色了

**Comment by treemore** [comment]
tabBarSelectedItemColor
这个好像生效了.好像不是实时的..

**Comment by listenzz** [comment]
这个是主题设置，在相关 View 创建前设置才有效

**Comment by treemore** [comment]
跟
https://github.com/listenzz/react-native-navigation-hybrid/issues/54
重复了
