### ISSUE TITLE
安卓编译失败

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#60]
![image](https://user-images.githubusercontent.com/5960864/46192499-e05dfa00-c32d-11e8-99d7-355bf100cb8e.png)
组件和 RN 都是最新版本

**Comment by listenzz** [comment]
好的，兼容性问题。可以先用回 ReactNativeHost, 对 release 没有影响

**Comment by yunuo-tech** [comment]
ios 也跑不起来，提示：'HBDViewController.h' file not found。  包括那个playground也是，报同样的错误。

**Comment by listenzz** [comment]
你是第一次跑，还是以前跑过？

**Comment by yunuo-tech** [comment]
第一次跑

**Comment by listenzz** [comment]
@yunuo-tech  iOS 需要用 cocoapods 安装依赖

**Comment by NrqhEIcsRi004** [comment]
0.57 是可以跑起来的。不过release 好像有问题，但是不确定是这个库的问题。
