### ISSUE TITLE
能否给个设置 tabbar 设置图片显示大小的参数。

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#61]
比如一张图是48*48，我想以24*24显示。在我因为某种情况下不能改图片尺寸的时候，我希望 tabbar 能有地方设置下图片的大小。

**Comment by listenzz** [comment]
加个后缀 `@2x ` 不 OK ？

**Comment by yunuo-tech** [comment]
经过测试并不 OK，而且这样每份图片都要准备三份，图片多了的话确实好麻烦。
之前用 react-navigation， 直接设置一张90*90的图片，然后有一套适配算法，直接设置图片的宽高即可。
或者如果能直接用<Image/>标签来设置就更好了。不仅是 tabbar，所有涉及到图片的地方都这样就完美了~~

**Comment by yunuo-tech** [comment]
OK
