### ISSUE TITLE
bundling failed

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#63]
react-native:0.57.2
react-native-navigation-hybrid:0.9.0-beta.2

bundling failed: Error: Unable to resolve module `./src/Router` from `xxx/node_modules/react-native-navigation-hybrid/index.js`: The module `./src/Router` could not be found from `xxx/node_modules/react-native-navigation-hybrid/index.js`

**Comment by listenzz** [comment]
是 git 的问题，Router 重命名为 router 了，删掉 node_modules 再试下

**Comment by NrqhEIcsRi004** [comment]
npm list 
└── react-native-navigation-hybrid@0.9.0-beta.2

**Comment by listenzz** [comment]
就是我把 Router.js 重名名为 router.js 了，git 识别不出来

**Comment by NrqhEIcsRi004** [comment]
删掉 node_modules 多次貌似无效果

**Comment by NrqhEIcsRi004** [comment]
好了 缓存问题
