### ISSUE TITLE
iOS 使用 updateTopBar 只能改变当前Screen的状态栏，能全局修改吗？

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#65]
this.props.garden.updateTopBar({
  topBarStyle: 'light-content', // 状态栏和导航栏前景色，可选值有 light-content 和 dark-content
});

**Comment by listenzz** [comment]
不能，想要全局改，只能通过 `Garden.setStyle`
