### ISSUE TITLE
screenBackgroundColor似乎并没有生效。

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#68]
![image](https://user-images.githubusercontent.com/5960864/47633103-ae87bf80-db87-11e8-91f2-1eb86d27fd9b.png)

背景设为了白色 #ffffff   但是依然是灰色的。

**Comment by yunuo-tech** [comment]
RN版本：0.57.4  组件版本：0.9.9

**Comment by listenzz** [comment]
有两处地方可以设置 screenBackgroundColor，其一是使用 Garden#setStyle 进行全局设置，其二是在 navigationItem 中进行局部设置。局部设置会覆盖全局设置。

**Comment by yunuo-tech** [comment]
@listenzz 我只在全局设置了screenBackgroundColor，确定其他地方没有设置，而且无论全局设置不设置screenBackgroundColor， 都是灰色，很奇怪，之前还没事的，今天升级到0.9.9  和 rn0.57.4后就这样了。然后我又重新建了个0.57.4的项目 没这个情况，所以问题应该就出在组件上

**Comment by yunuo-tech** [comment]
![image](https://user-images.githubusercontent.com/5960864/47634589-0543c800-db8d-11e8-8fa4-6ad3c0bb8493.png)
无论全局还是该页面 都设置了 screenBackgroundColor:"#ffffff"  都不生效。

**Comment by yunuo-tech** [comment]
抱歉 是我这的问题，一个 bug 隐藏的好深~
