### ISSUE TITLE
关于 tabbar 的两点建议

### ISSUE THREAD

**Issue by yunuo-tech** [listenzz/react-native-navigation-hybrid#71]
1. 是不是应该加几个参数 控制下 tabbar 的图标与文字之间的距离，还有文字大小等。

2.目前还实现不了 tabbar 中间凸起的效果吧？（如下图所示）能否考虑加上？

![image](https://user-images.githubusercontent.com/5960864/48262309-fdbdd200-e45c-11e8-9954-566f4bd280fa.png)

**Comment by listenzz** [comment]
0.11.0 开始支持[自定义TabBar](https://github.com/listenzz/react-native-navigation-hybrid/blob/master/doc/custom-tabbar.md)
