### ISSUE TITLE
关于样式控制的问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#73]
我可以调整底部菜单的背景颜色么？是否可以设置菜单中的文字是否显示？还是就是是否可以设置菜单栏图标凸起？是否可以做到头部的颜色渐变。。。

**Comment by listenzz** [comment]
底部菜单背景颜色可设置
不支持设置文字是否显示
菜单栏图标凸起是什么意思？
不支持头部颜色渐变，但是支持自定义整个头部，通过这种方式，可以实现头部颜色渐变

**Comment by lhh-sofy** [comment]
感谢您的回复。
如果是头部颜色渐变的话，那么安卓的状态栏怎么处理呢，也是需要渐变的。
自定义头部,貌似只是支持中间标题的自定义，没发现有整个头部的自定义，请指示一下啊。
图标凸起如下图所示
![wechatimg49](https://user-images.githubusercontent.com/13582183/48526426-953e7d00-e8c2-11e8-839d-03f224d65d2d.jpeg)

**Comment by yunuo-tech** [comment]
我也急需 tabbar 中间突出显示，或者文字不显示的功能

**Comment by lhh-sofy** [comment]
关于渐变的问题，暂时是隐藏掉顶部的header，然后完全使用rn的代码来实现渐变色。。
对原生不太熟悉，我可以使用第三方的tabbar组件么？如react-native-tab-navigator

**Comment by listenzz** [comment]
@lhh-sofy 可以使用 react-native-tab-navigator，但是要处理好头部的切换
