### ISSUE TITLE
如何监控底部菜单点击

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#77]
比如有四个tab，A,B,C,D四个tab页面
在tab A页面的时候，我点击A tab菜单，需要刷新A页面，怎么监听菜单点击
还有就是先判断当前页面是否已登陆，没登陆的时候直接跳转到登陆页面

**Comment by listenzz** [comment]
暂时没有方法监听 tab 点击事件

**Comment by lhh-sofy** [comment]
那新版本的话，能否加上该功能嗯，有时候挺需要的。

**Comment by listenzz** [comment]
好的

**Comment by listenzz** [comment]
#86
