### ISSUE TITLE
针对底部菜单问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#79]
1.ios跟安卓中，底部菜单的icon大小是多少， 3倍图是72么？最大是72么？
我在ios中图片的3倍图是66，显示的是正常的；但是在安卓中就有些错位了。
如图所示
<img width="364" alt="8acfad5a-5e7e-4a21-a85a-25cd90b98752" src="https://user-images.githubusercontent.com/13582183/48612572-5395fb00-e9c4-11e8-9575-47f4ff68b74b.png">
请问该如何进行菜单调整呢。。
2.安卓菜单页面貌似是一下子全部加载了，如果设置成点击菜单时候再加载，ios就是点击之后才加载页面

**Comment by listenzz** [comment]
底部菜单的 icon 是 24，3倍就是 72，你的 icon 是放在 rn 这边的吧，有没有给 @3x 这样的后缀

android 点击后再加载，需要在原生这边做优化，我有空做下。

**Comment by lhh-sofy** [comment]
有的,我最大的图片是66*66的，给的是@3x.png

**Comment by listenzz** [comment]
那就好奇怪了哈哈，不过还是有办法的。

在 Android 原生项目 app/src/main/res/values/styles.xml 添加如下配置

```xml
<dimen name="fixed_height_bottom_padding">8dp</dimen>
    <dimen name="fixed_height_top_padding_active">0dp</dimen>
    <dimen name="fixed_height_top_padding_inactive">0dp</dimen>
    <dimen name="fixed_icon_grid">24dp</dimen>
    <dimen name="fixed_label_active">12dp</dimen>
    <dimen name="fixed_label_inactive">12dp</dimen>
    <item name="fixed_label_active_to_inactive_ratio" format="float" type="dimen">1</item>
    <dimen name="badge_corner_radius">14dp</dimen>
    <dimen name="badge_height_padding">1dp</dimen>
    <dimen name="badge_width_padding">5dp</dimen>
    <dimen name="badge_text_size">12dp</dimen>
    <dimen name="badge_top_margin">2dp</dimen>
```
如果有问题，
调整fixed_height_bottom_padding、 fixed_icon_grid、fixed_label_active、fixed_label_inactive 的值看看
