### ISSUE TITLE
编译正常，生成ipa文件时候报错

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#80]
错误如下图所示：
![image](https://user-images.githubusercontent.com/13582183/48878648-528d1f80-ee43-11e8-9a6d-e7c2e1b43868.png)
希望指导一下，我这边的header search 文件如下所示
![image](https://user-images.githubusercontent.com/13582183/48878704-8a946280-ee43-11e8-870d-b9ef5025a54e.png)

**Comment by NrqhEIcsRi004** [comment]
可以生成ipa，你可能是其他库导致的

**Comment by listenzz** [comment]
#87
