### ISSUE TITLE
关于rn中使用pod的问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#83]
你好，我这边使用pod方式来管理rn组件的时候，发现没办法编译通过(rn项目).在模拟器环境中是可以的
错误如下图：
![wechatimg268](https://user-images.githubusercontent.com/13582183/49056366-759a4380-f236-11e8-9ab3-c695f162f4f3.jpeg)

**Comment by listenzz** [comment]
我们也是使用 cocoapods 来管理 RN 组件，没发现类似问题。
