### ISSUE TITLE
关于底部菜单点击监听事件

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#86]
你好，急需一个底部菜单的点击监听事件。在做底部菜单时候，有功能是点击弹出事件，而非正常的显示页面

**Comment by lhh-sofy** [comment]
非常感谢....

**Comment by lhh-sofy** [comment]
能否是在
《 配置全局样式》的时候，来监听菜单点击事件... 
如果是在当前菜单的页面监听的话，一旦监听后不是显示页面，就会有些问题.

**Comment by listenzz** [comment]
0.10.2 已发布
