### ISSUE TITLE
Garden.setStyle BarStyleDarkContent 没有效果

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#89]
`Garden.setStyle({
 topBarStyle:'BarStyleDarkContent'
});`
iOS上面可以动态设置？

**Comment by NrqhEIcsRi004** [comment]
使用 updateTabBar 和 setStyle 好像都没有什么用 android 和 ios 都测试了

**Comment by listenzz** [comment]
是指换肤吗？
