### ISSUE TITLE
tab能否设置图片？

### ISSUE THREAD

**Issue by VictorYuan666** [listenzz/react-native-navigation-hybrid#9]
现在文档中只看到设置iconfont 能否增加设置image的属性可以设置网络或本地图片，有一个inactiveImage 一个activeImage

**Comment by listenzz** [comment]
现在支持三种图片设置方式，iconfont，网络以及本地，配置方式会更新文档说明。原生底层支持为不同状态设置不同图片，会尽快增加此功能。

**Comment by listenzz** [comment]
已实现， 0.4.1 版本开始支持
