### ISSUE TITLE
如何控制 leftBarButtonItems 各个按钮之间的间距

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#90]
你好，现行的头部按钮组之间的间距是多少呢，是否可以自定义这个间距大小。

**Comment by listenzz** [comment]
间距是固定的，iOS 是系统默认间距，Android 没有间距，间距不能自定义。

但是可以自定义整个标题栏，摆放任何你想要的控件

**Comment by lhh-sofy** [comment]
那我能否通过变大图片来控制相应的间距呢.

**Comment by listenzz** [comment]
Android 是不能的，iOS 估计可以

**Comment by lhh-sofy** [comment]
好的，非常感谢
