### ISSUE TITLE
Navigator.setInterceptor 拦截问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#91]
在入口页面进行拦截时候，extras参数中获取不到sceneId;
没有办法进行拦截跳转页面
rn环境：0.57.7 ios
版本:0.10.2

**Comment by listenzz** [comment]
好的，知道了。下个版本修正。

现在可以通过 `const navigator = await Navigator.current()` 来获取一个 navigator
