### ISSUE TITLE
底部菜单无title情况下建议

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#93]
你好，不知可否实现在底部菜单无title情况下(对于原生不了解)，自动让按钮居中，如图所示
![image](https://user-images.githubusercontent.com/13582183/50197547-7c722d00-0382-11e9-9993-b7272243981a.png)

**Comment by lhh-sofy** [comment]
非常感谢🙏,这个路由导航非常好，比react-navigation的速度快多了。。

**Comment by listenzz** [comment]
0.11.0 开始支持[自定义TabBar](https://github.com/listenzz/react-native-navigation-hybrid/blob/master/doc/custom-tabbar.md)
