### ISSUE TITLE
关于showModal使用问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#95]
你好，在使用showModal的时候，如何传递组件到相应的modal页面里面呢。
目前是想做一个modal的基础页面，动画效果都在基础页面里面写；包含从下到上，从中间弹出等等。
我如何传递组件到该页面，目前不知如何处理。

**Comment by listenzz** [comment]
HOC, 组合模式，通过 props 传递 flag。

**Comment by lhh-sofy** [comment]
好的 ，多谢，已解决问题。
