### ISSUE TITLE
关于 自定义 TabBar 的使用问题

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#96]
你好，当我使用自定义 TabBar的时候，切换底部菜单按钮的时候，其余按钮会闪烁。ios跟android都会有这个问题。
rn：0.57.7
react-native-navigation-hybrid：0.11.0

**Comment by listenzz** [comment]
请参考 demo, 不闪。或者贴下代码。

**Comment by listenzz** [comment]
打个日志，看 componentDidMount 有没有重新执行。

**Comment by lhh-sofy** [comment]
我点击菜单按钮的时候，会重新render一次。

**Comment by listenzz** [comment]
是的。可以用 shouldComponentUpdate 来优化

**Comment by listenzz** [comment]
或者打个 release 包看看闪不闪，如果不闪，可以不优化。
demo 在 debug 下也是不闪的，建议仔细对比代码。

**Comment by listenzz** [comment]
这和 react 的 diff 算法有关系。每次切换菜单时，props 会改变，从而导致重新渲染。在渲染时，如果发现子组件的类型不一致，就会重新渲染整个子组件，也就是重新创建子组件。

请问在调用 `ReactRegistry.startRegisterComponent()`  时，有传递参数吗？该参数是如何实现的？是否在 render 中创建了组件？

**Comment by lhh-sofy** [comment]
感谢你的回复。。
我这边是这样使用的  
        ReactRegistry.registerComponent('BulgeTabBar', () => BulgeTabBar);
然后BulgeTabBar就是demo中的实例，除了中间的凸起图片是自己的

**Comment by listenzz** [comment]
我问的是 `ReactRegistry.startRegisterComponent` 不是 `ReactRegistry.registerComponent` 呢

**Comment by lhh-sofy** [comment]
不好意思，看错了，startRegisterComponent 这个也没有传递参数，是空的。

**Comment by lhh-sofy** [comment]
你好，我这边把视频转化成了gif文件。点击圈子的时候，又明显的加载效果。
![gif5](https://user-images.githubusercontent.com/13582183/50429709-05e1ac00-08fb-11e9-8826-6025be4fc166.gif)

**Comment by listenzz** [comment]
也就是说不是必现的。demo 中有 BulgeTabBar.js 和你这个需求是一样的。是参考这个来写的吗？

**Comment by lhh-sofy** [comment]
对的，一样的需求，一样的BulgeTabBar代码。。

**Comment by listenzz** [comment]
貌似只有第一次闪了下？

**Comment by listenzz** [comment]
第三个 tab 是怎么回事？

**Comment by lhh-sofy** [comment]
gif图上是比较少的，我这边很多次。我截一下log,这个是执行一次菜单点击之后的日志。CustomTabBar相当于每次都重新加载了一次，不是刷新。
<img width="1572" alt="wechat4371604f861bc7281ba828d8989e2b7f" src="https://user-images.githubusercontent.com/13582183/50430004-56a5d480-08fc-11e9-8637-93c03cba8af3.png">

**Comment by listenzz** [comment]
怀疑是高阶组件所致。

升级到 0.11.1

通过 `ReactRegistry.startRegisterComponent` 注入如下代码

```jsx
function withLog(WrappedComponent) {
  class Log extends Component {
    componentDidMount() {
      // 获取 displayName
      console.info(`displayName:${Log.displayName}`);
    }

    render() {
      return (
          <WrappedComponent {...this.props} />
      );
    }
  }
  Log.displayName = `WithLog(${WrappedComponent.displayName})`;
  return Log;
}

// 开始注册组件，即基本页面单元
ReactRegistry.startRegisterComponent(withRedux);
```

看下打印输出的是什么，

**Comment by lhh-sofy** [comment]
好的，我尝试一下。非常感谢。

**Comment by lhh-sofy** [comment]
你好，输出的一直都是  
`displayName:WithLog(WithNavigation(CustomTabBar))`

**Comment by listenzz** [comment]
好的，看不出有问题。

**Comment by listenzz** [comment]
怀疑是使用的第三方库，不恰当地 hook 了 `AppRegistry.registerComponent` 

有使用 antd 吗？

**Comment by listenzz** [comment]
问题还存在否？
