### ISSUE TITLE
Android 有时手势关闭会失效

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [listenzz/react-native-navigation-hybrid#97]

**Comment by listenzz** [comment]
哪个平台，如何发生的呢？

**Comment by listenzz** [comment]
0.11.0， 0.11.1， 0.11.2 都看看，谢谢

**Comment by NrqhEIcsRi004** [comment]
只测试了android 
0.11.0 Tab可以点
0.11.1  不行
0.11.2 run-android 报错
node_modules/react-native-navigation-hybrid/android/src/main/java/com/navigationhybrid/NavigationModule.java:214: 错误: 找不到符号
                List<AwesomeFragment> fragments = reactAppCompatActivity.getFragmentsAtAddedList();

**Comment by listenzz** [comment]
刚刚在我们的应用测试，是可以的。
你的项目应该是缓存所致。

**Comment by NrqhEIcsRi004** [comment]
各种清缓存 0.11.2 依然报错

0.11.2 run-android 报错
node_modules/react-native-navigation-hybrid/android/src/main/java/com/navigationhybrid/NavigationModule.java:214: 错误: 找不到符号
List fragments = reactAppCompatActivity.getFragmentsAtAddedList();

**Comment by NrqhEIcsRi004** [comment]
真的跑不起来，难受

**Comment by listenzz** [comment]
./gradlew build --refresh-dependencies 

试过没

**Comment by NrqhEIcsRi004** [comment]
试过还是报错。

**Comment by listenzz** [comment]
找到 node_modules/react-native-navigation-hybrid/android/build.gradle 
看里面是否有这行代码
api 'me.listenzz:navigation:2.1.3'

注意 0.11.4 的版本号是 2.1.2

如果有，说明 npm 包是没错的，就是 gradle 的缓存问题

用 AndroidStudio 运行你的 Android 项目

**Comment by NrqhEIcsRi004** [comment]
版本看起来是对的，我还是去用老版本。

**Comment by listenzz** [comment]
删掉 android 目录下 .gradle 和 .idea 这两个文件， 试试看

**Comment by NrqhEIcsRi004** [comment]
升级到0.11.6 

Android错误信息
node_modules/react-native-navigation-hybrid/android/src/main/java/com/navigationhybrid/GardenModule.java:238: 错误:不到符号
                        tabBarFragment.updateTabBar(bundle);
                                      ^
  符号:   方法 updateTabBar(Bundle)
  位置: 类型为TabBarFragment的变量 tabBarFragment


iOS错误信息
View Hierarchy is not ready when you call Navigator#currentRoute. In order to avoid this warning, please use Navigator#setRootLayoutUpdateListener coordinately.
View Hierarchy is not ready when you call Navigator#currentRoute.

**Comment by NrqhEIcsRi004** [comment]
是不是项目必须要发releases呀？

**Comment by listenzz** [comment]
Android 还是缓存问题，iOS 你照着提示来就可以了。

你需要借助 Navigator.setRootLayoutUpdateListener 来判断 UI 层级是否已经准备好。因为 Navigator.currentRoute 这个方法是有可能返回 null 的。

**Comment by NrqhEIcsRi004** [comment]
是不是要发releases了呀，打包各种报错不论ios和android，只有最新版的releases可用，

**Comment by listenzz** [comment]
什么意思呢？让我发个版？

**Comment by NrqhEIcsRi004** [comment]
<img width="184" alt="2019-01-14 8 34 28" src="https://user-images.githubusercontent.com/30352961/51115798-de1b9f00-183b-11e9-801d-e3935008ef02.png">

**Comment by NrqhEIcsRi004** [comment]
发到这个里面

**Comment by listenzz** [comment]
和这里没关系的呢

**Comment by NrqhEIcsRi004** [comment]
undefined is not an Object 'HBDEventEmitter.ON_COMPONENT_RESULT'

**Comment by NrqhEIcsRi004** [comment]
tabBarFragment.updateTabBar(bundle);
                                      ^
  符号:   方法 updateTabBar(Bundle)
  位置: 类型为TabBarFragment的变量 tabBarFragment

版本0.11.6
api 'me.listenzz:navigation:2.1.5'
api 'com.ashokvarma.android:bottom-navigation-bar:2.1.0'

**Comment by listenzz** [comment]
还是缓存问题。。

**Comment by listenzz** [comment]
![jietu20190114-231844](https://user-images.githubusercontent.com/4386370/51121599-c56ab380-1852-11e9-84df-f58a4cb68f4a.jpg)

![jietu20190114-231941](https://user-images.githubusercontent.com/4386370/51121648-e4694580-1852-11e9-9d0c-10ea24208706.jpg)

![jietu20190114-232203](https://user-images.githubusercontent.com/4386370/51121788-40cc6500-1853-11e9-9341-ef01210f3233.jpg)

![jietu20190114-232258](https://user-images.githubusercontent.com/4386370/51121840-5cd00680-1853-11e9-8063-897c508bd2ce.jpg)

**Comment by listenzz** [comment]
用 AndroidStudio 检查下你的项目

**Comment by NrqhEIcsRi004** [comment]
AndroidStudio 清缓存有没有什么终极解决方案？

**Comment by listenzz** [comment]
如果你用的是 Mac
cd 到你项目的 android 目录下
./gradlew clean
rm .gradle
rm .idea
rm  -rf  ~/.gradle
./gradlew build --refresh-dependencies
