### ISSUE TITLE
关于手势关闭时闪退问题 ，ios

### ISSUE THREAD

**Issue by lhh-sofy** [listenzz/react-native-navigation-hybrid#98]
你好，我这边做一个视频详情页面时候，点击返回按钮关闭时没有问题的，但是手势关闭时候，导致app闪退，ios测试，安卓没有测试。
push出来的页面
rn:0.57.7
react-native-navigation-hybrid:0.11.1
错误代码如下：
<img width="789" alt="8eac6675-210e-4fb2-9c11-3e43c2bd32cb" src="https://user-images.githubusercontent.com/13582183/50628230-30261000-0f72-11e9-9805-23dd07588075.png">

**Comment by listenzz** [comment]
必现还是偶现？

**Comment by lhh-sofy** [comment]
你好，能给我你的联系方式么？我这边封装ios原生组件的时候，有些问题解决不了。还能请教一下啊..

**Comment by listenzz** [comment]
留个邮箱，发微信你

**Comment by lhh-sofy** [comment]
好的，多谢。390097651@qq.com

**Comment by listenzz** [comment]
更新到 0.11.5 试下

**Comment by listenzz** [comment]
这个问题解决没？
